# Generated by Django 4.2.1 on 2023-05-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_cart_customuser_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cart',
            field=models.ManyToManyField(to='users.cart'),
        ),
    ]
